export {default as Home} from './home/Home';
export {default as Auth} from './auth/Auth';
export {default as Case} from './case/Case';
export {default as Project} from './project/Project';
export {default as Mypage} from './mypage/Mypage';
export {default as Works} from './works/Works';
export {default as WorksDetail} from './works/WorksDetail';
export {default as Alert} from './alert/Alert';
export {default as DashBoard} from './dashboard/DashBoard';